# Generated by Django 5.2.16 on 2026-07-31 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrositePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('theme', models.CharField(default='default', help_text='Choose a brand theme variant for this microsite. Controls colour palette and typography applied via CSS.', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date/time. After this the page can be automatically unpublished or archived by a scheduled task.', null=True)),
                ('builder_json', models.JSONField(blank=True, default=dict, help_text='Constrained block schema produced by the visual builder. Only approved block types and props are accepted.')),
                ('rendered_preview', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Microsite page',
                'verbose_name_plural': 'Microsite pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
